baseURL = 'https://kaminate.github.io/'
languageCode = 'en-us'
title = 'n4735 n0735'
theme = 'PaperMod'

[markup.tableOfContents]
    endLevel = 6
    startLevel = 2

[params]
# list of subfolders in ./content/ to show on the main page
# Let the papermod theme show content from multiple folders
# instead of defaulting to the folder with the most entries
mainSections = ['foo', 'posts', 'website']

custom_css = ["css/custom.css"]
custom_js = [ "js/custom.js"]

# Hide the "Powered by Hugo and PaperMod" footer
# ( see themes/PaperMod/layouts.partials/footer.html )
hideFooter = "true"

# Allow comments on posts
comments = "true"

# Show Next and Prev buttons at the bottom of each post
# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#other-posts-suggestion-below-a-post
# https://push.blue/posts/20220718-reverse-papermodnavlinks/
ShowPostNavLinks = "true"

[params.homeInfoParams]
# what to show on the home page
Title = "Hello"
Content = ""

# note: if you typo socialIcons as socalIcons,
# there is no error message telling you what was wrong
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/n8tak"

[[params.socialIcons]]
name = "email"
url = "mailto:gamedevnate@gmail.com"


#asdf
