baseURL = 'https://kaminate.github.io/'
locale='en-us'
title = 'n4735 n0735'
theme = [ 'hugo-embed-pdf-shortcode', 'PaperMod' ]
enableInlineShortcodes=true

[markup.tableOfContents]
    endLevel = 6
    startLevel = 2

[menu]
  main = [
      { name = "Origami", url = "/pages/origami", weight = 1 },
      { name = "Gamedev", url = "/pages/gamedev", weight = 2 },
      { name = "About", url = "/pages/about", weight = 3 },
      { name = "Resume", url = "/pages/resume", weight = 4 },
  ]
  

[params]

    profileMode.enabled = true
    profileMode.title= "Nate Park"
    profileMode.subtitle= "Origami Artist | Video Game Programmer"

    # (these show if profile mode is disabled)
    homeInfoParams.Title = "Nate Park"
    homeInfoParams.Content = "Origami Artist | Game Programmer"

    # list of subfolders in ./content/ to show on the main page
    # Let the papermod theme show content from multiple folders
    # instead of defaulting to the folder with the most entries
    # mainSections = ['foo', 'posts', 'website', 'pages']
    mainSections = []

    custom_css = ["css/custom.css"]
    custom_js = [ "js/custom.js"]

    # Hide the "Powered by Hugo and PaperMod" footer (themes/PaperMod/layouts.partials/footer.html )
    # Note that this does not hide layouts/partials/extend_footer.html
    hideFooter = "true"

    comments = "true" # Allow comments on posts

    # Show Next and Prev buttons at the bottom of each post
    # https://github.com/adityatelange/hugo-PaperMod/wiki/Features#other-posts-suggestion-below-a-post
    # https://push.blue/posts/20220718-reverse-papermodnavlinks/
    ShowPostNavLinks = "true"

    socialIcons=[
      { name = "github", url = "https://github.com/Kaminate" },
      { name = "twitter", url = "https://twitter.com/n8tak" },
      { name = "linkedin", url = "https://www.linkedin.com/in/parknathan" },
      { name = "email", url = "mailto:gamedevnate@gmail.com" },
    ]


